
#- name:		Debug
#  debug:
#    var: hostvars[inventory_hostname.ec2_private_ip_address]

- name:		Enable EPEL
  command: 	yum-config-manager --enable epel
  become: 	true

- name:		Install SIPP
  yum:		
    name:	https://dl.fedoraproject.org/pub/epel/7/x86_64/s/sipp-3.5.0-3.el7.x86_64.rpm
    state:	present
  become:	true

- name:		Install additional packages
  yum:
    name:	"{{ item }}"
    state:	present
  become:	true
  with_items:
    - tcpdump
    - git

- name:		Clone testing repo
  git:
    repo:	https://github.com/jdeglopper/aws-sipp
    dest:	/home/ec2-user/sipp

#- name:		Save private IPs
#  template:
#    src:	sipp-ip.j2
#    dest:	/home/ec2-user/sipp-ip.sh
#    owner:	ec2-user
#    force:	yes

