
- name:		Enable EPEL
  command: 	yum-config-manager --enable epel
  become: 	true
  
- name:		Install SIPP
  yum:		
    name:	https://dl.fedoraproject.org/pub/epel/7/x86_64/s/sipp-3.5.0-3.el7.x86_64.rpm
    state:	present
  become:	true
